# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Fisher_0_0_1(object):
    def setupUi(self, Fisher_0_0_1):
        Fisher_0_0_1.setObjectName("Fisher_0_0_1")
        Fisher_0_0_1.resize(418, 364)
        self.centralwidget = QtWidgets.QWidget(Fisher_0_0_1)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 131, 41))
        self.textEdit.setObjectName("textEdit")
        self.port = QtWidgets.QComboBox(self.centralwidget)
        self.port.setGeometry(QtCore.QRect(260, 20, 131, 41))
        self.port.setObjectName("port")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 90, 171, 41))
        self.textEdit_2.setObjectName("textEdit_2")
        self.speed = QtWidgets.QComboBox(self.centralwidget)
        self.speed.setGeometry(QtCore.QRect(260, 90, 131, 41))
        self.speed.setObjectName("speed")
        self.connect_Button = QtWidgets.QPushButton(self.centralwidget)
        self.connect_Button.setGeometry(QtCore.QRect(120, 150, 171, 51))
        self.connect_Button.setObjectName("connect_Button")
        self.start_Button = QtWidgets.QPushButton(self.centralwidget)
        self.start_Button.setGeometry(QtCore.QRect(30, 220, 161, 81))
        self.start_Button.setObjectName("start_Button")
        self.stop_Button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_Button.setGeometry(QtCore.QRect(220, 220, 171, 81))
        self.stop_Button.setObjectName("stop_Button")
        Fisher_0_0_1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Fisher_0_0_1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 418, 21))
        self.menubar.setObjectName("menubar")
        Fisher_0_0_1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Fisher_0_0_1)
        self.statusbar.setObjectName("statusbar")
        Fisher_0_0_1.setStatusBar(self.statusbar)

        self.retranslateUi(Fisher_0_0_1)
        QtCore.QMetaObject.connectSlotsByName(Fisher_0_0_1)

    def retranslateUi(self, Fisher_0_0_1):
        _translate = QtCore.QCoreApplication.translate
        Fisher_0_0_1.setWindowTitle(_translate("Fisher_0_0_1", "Fisher_0_0_1"))
        self.textEdit.setHtml(_translate("Fisher_0_0_1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Выбери порт:</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("Fisher_0_0_1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Выбери скорость:</span></p></body></html>"))
        self.connect_Button.setText(_translate("Fisher_0_0_1", "Подключиться"))
        self.start_Button.setText(_translate("Fisher_0_0_1", "Старт"))
        self.stop_Button.setText(_translate("Fisher_0_0_1", "Стоп"))
